#include: package:very_good_analysis/analysis_options.yaml
#analyzer:
#  exclude:
#    - lib/l10n/gen/*
#linter:
#  rules:
#    public_member_api_docs: false
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
